//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CIPMSModel", "FK_tblFederationCampsContactDetails_tblCamps", "tblCamp", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.tblCamp), "tblFederationCampsContactDetail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.tblFederationCampsContactDetail))]
[assembly: EdmRelationshipAttribute("CIPMSModel", "FK_tblFederationCamps_Camps", "tblCamp", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Model.tblCamp), "tblFederationCamp", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Model.tblFederationCamp))]

#endregion

namespace Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CIPMSEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CIPMSEntities1 object using the connection string found in the 'CIPMSEntities1' section of the application configuration file.
        /// </summary>
        public CIPMSEntities1() : base("name=CIPMSEntities1", "CIPMSEntities1")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CIPMSEntities1 object.
        /// </summary>
        public CIPMSEntities1(string connectionString) : base(connectionString, "CIPMSEntities1")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CIPMSEntities1 object.
        /// </summary>
        public CIPMSEntities1(EntityConnection connection) : base(connection, "CIPMSEntities1")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblFederationGrade> tblFederationGrades
        {
            get
            {
                if ((_tblFederationGrades == null))
                {
                    _tblFederationGrades = base.CreateObjectSet<tblFederationGrade>("tblFederationGrades");
                }
                return _tblFederationGrades;
            }
        }
        private ObjectSet<tblFederationGrade> _tblFederationGrades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMetaFederationGrade> tblMetaFederationGrades
        {
            get
            {
                if ((_tblMetaFederationGrades == null))
                {
                    _tblMetaFederationGrades = base.CreateObjectSet<tblMetaFederationGrade>("tblMetaFederationGrades");
                }
                return _tblMetaFederationGrades;
            }
        }
        private ObjectSet<tblMetaFederationGrade> _tblMetaFederationGrades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCamp> tblCamps
        {
            get
            {
                if ((_tblCamps == null))
                {
                    _tblCamps = base.CreateObjectSet<tblCamp>("tblCamps");
                }
                return _tblCamps;
            }
        }
        private ObjectSet<tblCamp> _tblCamps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMetaCamp> tblMetaCamps
        {
            get
            {
                if ((_tblMetaCamps == null))
                {
                    _tblMetaCamps = base.CreateObjectSet<tblMetaCamp>("tblMetaCamps");
                }
                return _tblMetaCamps;
            }
        }
        private ObjectSet<tblMetaCamp> _tblMetaCamps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblCampYear> tblCampYears
        {
            get
            {
                if ((_tblCampYears == null))
                {
                    _tblCampYears = base.CreateObjectSet<tblCampYear>("tblCampYears");
                }
                return _tblCampYears;
            }
        }
        private ObjectSet<tblCampYear> _tblCampYears;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblNationalCamp> tblNationalCamps
        {
            get
            {
                if ((_tblNationalCamps == null))
                {
                    _tblNationalCamps = base.CreateObjectSet<tblNationalCamp>("tblNationalCamps");
                }
                return _tblNationalCamps;
            }
        }
        private ObjectSet<tblNationalCamp> _tblNationalCamps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblFederationCampsContactDetail> tblFederationCampsContactDetails
        {
            get
            {
                if ((_tblFederationCampsContactDetails == null))
                {
                    _tblFederationCampsContactDetails = base.CreateObjectSet<tblFederationCampsContactDetail>("tblFederationCampsContactDetails");
                }
                return _tblFederationCampsContactDetails;
            }
        }
        private ObjectSet<tblFederationCampsContactDetail> _tblFederationCampsContactDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblFederationCamp> tblFederationCamps
        {
            get
            {
                if ((_tblFederationCamps == null))
                {
                    _tblFederationCamps = base.CreateObjectSet<tblFederationCamp>("tblFederationCamps");
                }
                return _tblFederationCamps;
            }
        }
        private ObjectSet<tblFederationCamp> _tblFederationCamps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSynagogue> tblSynagogues
        {
            get
            {
                if ((_tblSynagogues == null))
                {
                    _tblSynagogues = base.CreateObjectSet<tblSynagogue>("tblSynagogues");
                }
                return _tblSynagogues;
            }
        }
        private ObjectSet<tblSynagogue> _tblSynagogues;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblJCC> tblJCCs
        {
            get
            {
                if ((_tblJCCs == null))
                {
                    _tblJCCs = base.CreateObjectSet<tblJCC>("tblJCCs");
                }
                return _tblJCCs;
            }
        }
        private ObjectSet<tblJCC> _tblJCCs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUserCamp> tblUserCamps
        {
            get
            {
                if ((_tblUserCamps == null))
                {
                    _tblUserCamps = base.CreateObjectSet<tblUserCamp>("tblUserCamps");
                }
                return _tblUserCamps;
            }
        }
        private ObjectSet<tblUserCamp> _tblUserCamps;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblFedCampGrant> tblFedCampGrants
        {
            get
            {
                if ((_tblFedCampGrants == null))
                {
                    _tblFedCampGrants = base.CreateObjectSet<tblFedCampGrant>("tblFedCampGrants");
                }
                return _tblFedCampGrants;
            }
        }
        private ObjectSet<tblFedCampGrant> _tblFedCampGrants;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblFederationGrades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblFederationGrades(tblFederationGrade tblFederationGrade)
        {
            base.AddObject("tblFederationGrades", tblFederationGrade);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMetaFederationGrades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMetaFederationGrades(tblMetaFederationGrade tblMetaFederationGrade)
        {
            base.AddObject("tblMetaFederationGrades", tblMetaFederationGrade);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCamps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCamps(tblCamp tblCamp)
        {
            base.AddObject("tblCamps", tblCamp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMetaCamps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMetaCamps(tblMetaCamp tblMetaCamp)
        {
            base.AddObject("tblMetaCamps", tblMetaCamp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblCampYears EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblCampYears(tblCampYear tblCampYear)
        {
            base.AddObject("tblCampYears", tblCampYear);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblNationalCamps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblNationalCamps(tblNationalCamp tblNationalCamp)
        {
            base.AddObject("tblNationalCamps", tblNationalCamp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblFederationCampsContactDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblFederationCampsContactDetails(tblFederationCampsContactDetail tblFederationCampsContactDetail)
        {
            base.AddObject("tblFederationCampsContactDetails", tblFederationCampsContactDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblFederationCamps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblFederationCamps(tblFederationCamp tblFederationCamp)
        {
            base.AddObject("tblFederationCamps", tblFederationCamp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSynagogues EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSynagogues(tblSynagogue tblSynagogue)
        {
            base.AddObject("tblSynagogues", tblSynagogue);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblJCCs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblJCCs(tblJCC tblJCC)
        {
            base.AddObject("tblJCCs", tblJCC);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUserCamps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUserCamps(tblUserCamp tblUserCamp)
        {
            base.AddObject("tblUserCamps", tblUserCamp);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblFedCampGrants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblFedCampGrants(tblFedCampGrant tblFedCampGrant)
        {
            base.AddObject("tblFedCampGrants", tblFedCampGrant);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public ObjectResult<tblCamp> uspCampsDelete(Nullable<global::System.Int32> campYearID)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<tblCamp>("uspCampsDelete", campYearIDParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public ObjectResult<tblCamp> uspCampsDelete(Nullable<global::System.Int32> campYearID, MergeOption mergeOption)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<tblCamp>("uspCampsDelete", mergeOption, campYearIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public ObjectResult<tblFederationGrade> uspFederationGradesDelete(Nullable<global::System.Int32> campYearID)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<tblFederationGrade>("uspFederationGradesDelete", campYearIDParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public ObjectResult<tblFederationGrade> uspFederationGradesDelete(Nullable<global::System.Int32> campYearID, MergeOption mergeOption)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<tblFederationGrade>("uspFederationGradesDelete", mergeOption, campYearIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public int uspFedCampGrantDelete(Nullable<global::System.Int32> campYearID)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("uspFedCampGrantDelete", campYearIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public ObjectResult<tblNationalCamp> uspNationalCampsDelete(Nullable<global::System.Int32> campYearID)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<tblNationalCamp>("uspNationalCampsDelete", campYearIDParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public ObjectResult<tblNationalCamp> uspNationalCampsDelete(Nullable<global::System.Int32> campYearID, MergeOption mergeOption)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<tblNationalCamp>("uspNationalCampsDelete", mergeOption, campYearIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public ObjectResult<tblFederationCampsContactDetail> uspFedCampsContactsDelete(Nullable<global::System.Int32> campYearID)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<tblFederationCampsContactDetail>("uspFedCampsContactsDelete", campYearIDParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="campYearID">No Metadata Documentation available.</param>
        public ObjectResult<tblFederationCampsContactDetail> uspFedCampsContactsDelete(Nullable<global::System.Int32> campYearID, MergeOption mergeOption)
        {
            ObjectParameter campYearIDParameter;
            if (campYearID.HasValue)
            {
                campYearIDParameter = new ObjectParameter("CampYearID", campYearID);
            }
            else
            {
                campYearIDParameter = new ObjectParameter("CampYearID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<tblFederationCampsContactDetail>("uspFedCampsContactsDelete", mergeOption, campYearIDParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblCamp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCamp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCamp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblCamp CreatetblCamp(global::System.Int64 id)
        {
            tblCamp tblCamp = new tblCamp();
            tblCamp.ID = id;
            return tblCamp;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, "State");
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Int32> _State;
        partial void OnStateChanging(Nullable<global::System.Int32> value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Inactive
        {
            get
            {
                return _Inactive;
            }
            set
            {
                OnInactiveChanging(value);
                ReportPropertyChanging("Inactive");
                _Inactive = StructuralObject.SetValidValue(value, "Inactive");
                ReportPropertyChanged("Inactive");
                OnInactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Inactive;
        partial void OnInactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnInactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CampYearID
        {
            get
            {
                return _CampYearID;
            }
            set
            {
                OnCampYearIDChanging(value);
                ReportPropertyChanging("CampYearID");
                _CampYearID = StructuralObject.SetValidValue(value, "CampYearID");
                ReportPropertyChanged("CampYearID");
                OnCampYearIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CampYearID;
        partial void OnCampYearIDChanging(Nullable<global::System.Int32> value);
        partial void OnCampYearIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsManual
        {
            get
            {
                return _IsManual;
            }
            set
            {
                OnIsManualChanging(value);
                ReportPropertyChanging("IsManual");
                _IsManual = StructuralObject.SetValidValue(value, "IsManual");
                ReportPropertyChanged("IsManual");
                OnIsManualChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsManual;
        partial void OnIsManualChanging(Nullable<global::System.Boolean> value);
        partial void OnIsManualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> JDataID
        {
            get
            {
                return _JDataID;
            }
            set
            {
                OnJDataIDChanging(value);
                ReportPropertyChanging("JDataID");
                _JDataID = StructuralObject.SetValidValue(value, "JDataID");
                ReportPropertyChanged("JDataID");
                OnJDataIDChanged();
            }
        }
        private Nullable<global::System.Int32> _JDataID;
        partial void OnJDataIDChanging(Nullable<global::System.Int32> value);
        partial void OnJDataIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsWestCamp
        {
            get
            {
                return _IsWestCamp;
            }
            set
            {
                OnIsWestCampChanging(value);
                ReportPropertyChanging("IsWestCamp");
                _IsWestCamp = StructuralObject.SetValidValue(value, "IsWestCamp");
                ReportPropertyChanged("IsWestCamp");
                OnIsWestCampChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsWestCamp;
        partial void OnIsWestCampChanging(Nullable<global::System.Boolean> value);
        partial void OnIsWestCampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsAdamahCamp
        {
            get
            {
                return _IsAdamahCamp;
            }
            set
            {
                OnIsAdamahCampChanging(value);
                ReportPropertyChanging("IsAdamahCamp");
                _IsAdamahCamp = StructuralObject.SetValidValue(value, "IsAdamahCamp");
                ReportPropertyChanged("IsAdamahCamp");
                OnIsAdamahCampChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsAdamahCamp;
        partial void OnIsAdamahCampChanging(Nullable<global::System.Boolean> value);
        partial void OnIsAdamahCampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsURJCamp
        {
            get
            {
                return _IsURJCamp;
            }
            set
            {
                OnIsURJCampChanging(value);
                ReportPropertyChanging("IsURJCamp");
                _IsURJCamp = StructuralObject.SetValidValue(value, "IsURJCamp");
                ReportPropertyChanged("IsURJCamp");
                OnIsURJCampChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsURJCamp;
        partial void OnIsURJCampChanging(Nullable<global::System.Boolean> value);
        partial void OnIsURJCampChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CIPMSModel", "FK_tblFederationCampsContactDetails_tblCamps", "tblFederationCampsContactDetail")]
        public EntityCollection<tblFederationCampsContactDetail> tblFederationCampsContactDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblFederationCampsContactDetail>("CIPMSModel.FK_tblFederationCampsContactDetails_tblCamps", "tblFederationCampsContactDetail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblFederationCampsContactDetail>("CIPMSModel.FK_tblFederationCampsContactDetails_tblCamps", "tblFederationCampsContactDetail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CIPMSModel", "FK_tblFederationCamps_Camps", "tblFederationCamp")]
        public EntityCollection<tblFederationCamp> tblFederationCamps
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblFederationCamp>("CIPMSModel.FK_tblFederationCamps_Camps", "tblFederationCamp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblFederationCamp>("CIPMSModel.FK_tblFederationCamps_Camps", "tblFederationCamp", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblCampYear")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblCampYear : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblCampYear object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="campYear">Initial value of the CampYear property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="currentYear">Initial value of the CurrentYear property.</param>
        public static tblCampYear CreatetblCampYear(global::System.Int32 id, global::System.Int32 campYear, global::System.DateTime startDate, global::System.DateTime endDate, global::System.Boolean currentYear)
        {
            tblCampYear tblCampYear = new tblCampYear();
            tblCampYear.ID = id;
            tblCampYear.CampYear = campYear;
            tblCampYear.StartDate = startDate;
            tblCampYear.EndDate = endDate;
            tblCampYear.CurrentYear = currentYear;
            return tblCampYear;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampYear
        {
            get
            {
                return _CampYear;
            }
            set
            {
                OnCampYearChanging(value);
                ReportPropertyChanging("CampYear");
                _CampYear = StructuralObject.SetValidValue(value, "CampYear");
                ReportPropertyChanged("CampYear");
                OnCampYearChanged();
            }
        }
        private global::System.Int32 _CampYear;
        partial void OnCampYearChanging(global::System.Int32 value);
        partial void OnCampYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value, "StartDate");
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value, "EndDate");
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CurrentYear
        {
            get
            {
                return _CurrentYear;
            }
            set
            {
                OnCurrentYearChanging(value);
                ReportPropertyChanging("CurrentYear");
                _CurrentYear = StructuralObject.SetValidValue(value, "CurrentYear");
                ReportPropertyChanged("CurrentYear");
                OnCurrentYearChanged();
            }
        }
        private global::System.Boolean _CurrentYear;
        partial void OnCurrentYearChanging(global::System.Boolean value);
        partial void OnCurrentYearChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblFedCampGrant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblFedCampGrant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblFedCampGrant object.
        /// </summary>
        /// <param name="federationID">Initial value of the FederationID property.</param>
        /// <param name="campID">Initial value of the CampID property.</param>
        /// <param name="campYearID">Initial value of the CampYearID property.</param>
        /// <param name="timeInCamp">Initial value of the TimeInCamp property.</param>
        /// <param name="daysAtLeast">Initial value of the DaysAtLeast property.</param>
        /// <param name="grantAmount">Initial value of the GrantAmount property.</param>
        public static tblFedCampGrant CreatetblFedCampGrant(global::System.Int32 federationID, global::System.Int32 campID, global::System.Int32 campYearID, global::System.Int32 timeInCamp, global::System.Int32 daysAtLeast, global::System.Double grantAmount)
        {
            tblFedCampGrant tblFedCampGrant = new tblFedCampGrant();
            tblFedCampGrant.FederationID = federationID;
            tblFedCampGrant.CampID = campID;
            tblFedCampGrant.CampYearID = campYearID;
            tblFedCampGrant.TimeInCamp = timeInCamp;
            tblFedCampGrant.DaysAtLeast = daysAtLeast;
            tblFedCampGrant.GrantAmount = grantAmount;
            return tblFedCampGrant;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FederationID
        {
            get
            {
                return _FederationID;
            }
            set
            {
                if (_FederationID != value)
                {
                    OnFederationIDChanging(value);
                    ReportPropertyChanging("FederationID");
                    _FederationID = StructuralObject.SetValidValue(value, "FederationID");
                    ReportPropertyChanged("FederationID");
                    OnFederationIDChanged();
                }
            }
        }
        private global::System.Int32 _FederationID;
        partial void OnFederationIDChanging(global::System.Int32 value);
        partial void OnFederationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampID
        {
            get
            {
                return _CampID;
            }
            set
            {
                if (_CampID != value)
                {
                    OnCampIDChanging(value);
                    ReportPropertyChanging("CampID");
                    _CampID = StructuralObject.SetValidValue(value, "CampID");
                    ReportPropertyChanged("CampID");
                    OnCampIDChanged();
                }
            }
        }
        private global::System.Int32 _CampID;
        partial void OnCampIDChanging(global::System.Int32 value);
        partial void OnCampIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampYearID
        {
            get
            {
                return _CampYearID;
            }
            set
            {
                if (_CampYearID != value)
                {
                    OnCampYearIDChanging(value);
                    ReportPropertyChanging("CampYearID");
                    _CampYearID = StructuralObject.SetValidValue(value, "CampYearID");
                    ReportPropertyChanged("CampYearID");
                    OnCampYearIDChanged();
                }
            }
        }
        private global::System.Int32 _CampYearID;
        partial void OnCampYearIDChanging(global::System.Int32 value);
        partial void OnCampYearIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimeInCamp
        {
            get
            {
                return _TimeInCamp;
            }
            set
            {
                if (_TimeInCamp != value)
                {
                    OnTimeInCampChanging(value);
                    ReportPropertyChanging("TimeInCamp");
                    _TimeInCamp = StructuralObject.SetValidValue(value, "TimeInCamp");
                    ReportPropertyChanged("TimeInCamp");
                    OnTimeInCampChanged();
                }
            }
        }
        private global::System.Int32 _TimeInCamp;
        partial void OnTimeInCampChanging(global::System.Int32 value);
        partial void OnTimeInCampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DaysAtLeast
        {
            get
            {
                return _DaysAtLeast;
            }
            set
            {
                if (_DaysAtLeast != value)
                {
                    OnDaysAtLeastChanging(value);
                    ReportPropertyChanging("DaysAtLeast");
                    _DaysAtLeast = StructuralObject.SetValidValue(value, "DaysAtLeast");
                    ReportPropertyChanged("DaysAtLeast");
                    OnDaysAtLeastChanged();
                }
            }
        }
        private global::System.Int32 _DaysAtLeast;
        partial void OnDaysAtLeastChanging(global::System.Int32 value);
        partial void OnDaysAtLeastChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double GrantAmount
        {
            get
            {
                return _GrantAmount;
            }
            set
            {
                OnGrantAmountChanging(value);
                ReportPropertyChanging("GrantAmount");
                _GrantAmount = StructuralObject.SetValidValue(value, "GrantAmount");
                ReportPropertyChanged("GrantAmount");
                OnGrantAmountChanged();
            }
        }
        private global::System.Double _GrantAmount;
        partial void OnGrantAmountChanging(global::System.Double value);
        partial void OnGrantAmountChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblFederationCamp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblFederationCamp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblFederationCamp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="federationID">Initial value of the FederationID property.</param>
        public static tblFederationCamp CreatetblFederationCamp(global::System.Int64 id, global::System.Int32 federationID)
        {
            tblFederationCamp tblFederationCamp = new tblFederationCamp();
            tblFederationCamp.ID = id;
            tblFederationCamp.FederationID = federationID;
            return tblFederationCamp;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FederationID
        {
            get
            {
                return _FederationID;
            }
            set
            {
                OnFederationIDChanging(value);
                ReportPropertyChanging("FederationID");
                _FederationID = StructuralObject.SetValidValue(value, "FederationID");
                ReportPropertyChanged("FederationID");
                OnFederationIDChanged();
            }
        }
        private global::System.Int32 _FederationID;
        partial void OnFederationIDChanging(global::System.Int32 value);
        partial void OnFederationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Inactive
        {
            get
            {
                return _Inactive;
            }
            set
            {
                OnInactiveChanging(value);
                ReportPropertyChanging("Inactive");
                _Inactive = StructuralObject.SetValidValue(value, "Inactive");
                ReportPropertyChanged("Inactive");
                OnInactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _Inactive;
        partial void OnInactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnInactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CampYearID
        {
            get
            {
                return _CampYearID;
            }
            set
            {
                OnCampYearIDChanging(value);
                ReportPropertyChanging("CampYearID");
                _CampYearID = StructuralObject.SetValidValue(value, "CampYearID");
                ReportPropertyChanged("CampYearID");
                OnCampYearIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CampYearID;
        partial void OnCampYearIDChanging(Nullable<global::System.Int32> value);
        partial void OnCampYearIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CIPMSModel", "FK_tblFederationCamps_Camps", "tblCamp")]
        public tblCamp tblCamp
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCamp>("CIPMSModel.FK_tblFederationCamps_Camps", "tblCamp").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCamp>("CIPMSModel.FK_tblFederationCamps_Camps", "tblCamp").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCamp> tblCampReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCamp>("CIPMSModel.FK_tblFederationCamps_Camps", "tblCamp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCamp>("CIPMSModel.FK_tblFederationCamps_Camps", "tblCamp", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblFederationCampsContactDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblFederationCampsContactDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblFederationCampsContactDetail object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="federationID">Initial value of the FederationID property.</param>
        public static tblFederationCampsContactDetail CreatetblFederationCampsContactDetail(global::System.Int32 id, global::System.Int32 federationID)
        {
            tblFederationCampsContactDetail tblFederationCampsContactDetail = new tblFederationCampsContactDetail();
            tblFederationCampsContactDetail.ID = id;
            tblFederationCampsContactDetail.FederationID = federationID;
            return tblFederationCampsContactDetail;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FederationID
        {
            get
            {
                return _FederationID;
            }
            set
            {
                OnFederationIDChanging(value);
                ReportPropertyChanging("FederationID");
                _FederationID = StructuralObject.SetValidValue(value, "FederationID");
                ReportPropertyChanged("FederationID");
                OnFederationIDChanged();
            }
        }
        private global::System.Int32 _FederationID;
        partial void OnFederationIDChanging(global::System.Int32 value);
        partial void OnFederationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                OnContactChanging(value);
                ReportPropertyChanging("Contact");
                _Contact = StructuralObject.SetValidValue(value, true, "Contact");
                ReportPropertyChanged("Contact");
                OnContactChanged();
            }
        }
        private global::System.String _Contact;
        partial void OnContactChanging(global::System.String value);
        partial void OnContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true, "Phone");
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavigationURL
        {
            get
            {
                return _NavigationURL;
            }
            set
            {
                OnNavigationURLChanging(value);
                ReportPropertyChanging("NavigationURL");
                _NavigationURL = StructuralObject.SetValidValue(value, true, "NavigationURL");
                ReportPropertyChanged("NavigationURL");
                OnNavigationURLChanged();
            }
        }
        private global::System.String _NavigationURL;
        partial void OnNavigationURLChanging(global::System.String value);
        partial void OnNavigationURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ParentInfoPreviousClickURL
        {
            get
            {
                return _ParentInfoPreviousClickURL;
            }
            set
            {
                OnParentInfoPreviousClickURLChanging(value);
                ReportPropertyChanging("ParentInfoPreviousClickURL");
                _ParentInfoPreviousClickURL = StructuralObject.SetValidValue(value, true, "ParentInfoPreviousClickURL");
                ReportPropertyChanged("ParentInfoPreviousClickURL");
                OnParentInfoPreviousClickURLChanged();
            }
        }
        private global::System.String _ParentInfoPreviousClickURL;
        partial void OnParentInfoPreviousClickURLChanging(global::System.String value);
        partial void OnParentInfoPreviousClickURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CampYearID
        {
            get
            {
                return _CampYearID;
            }
            set
            {
                OnCampYearIDChanging(value);
                ReportPropertyChanging("CampYearID");
                _CampYearID = StructuralObject.SetValidValue(value, "CampYearID");
                ReportPropertyChanged("CampYearID");
                OnCampYearIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CampYearID;
        partial void OnCampYearIDChanging(Nullable<global::System.Int32> value);
        partial void OnCampYearIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CIPMSModel", "FK_tblFederationCampsContactDetails_tblCamps", "tblCamp")]
        public tblCamp tblCamp
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCamp>("CIPMSModel.FK_tblFederationCampsContactDetails_tblCamps", "tblCamp").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCamp>("CIPMSModel.FK_tblFederationCampsContactDetails_tblCamps", "tblCamp").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblCamp> tblCampReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblCamp>("CIPMSModel.FK_tblFederationCampsContactDetails_tblCamps", "tblCamp");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblCamp>("CIPMSModel.FK_tblFederationCampsContactDetails_tblCamps", "tblCamp", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblFederationGrade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblFederationGrade : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblFederationGrade object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="federationID">Initial value of the FederationID property.</param>
        /// <param name="eligibleGrade">Initial value of the EligibleGrade property.</param>
        /// <param name="campYearID">Initial value of the CampYearID property.</param>
        public static tblFederationGrade CreatetblFederationGrade(global::System.Int32 id, global::System.Int32 federationID, global::System.Int32 eligibleGrade, global::System.Int32 campYearID)
        {
            tblFederationGrade tblFederationGrade = new tblFederationGrade();
            tblFederationGrade.ID = id;
            tblFederationGrade.FederationID = federationID;
            tblFederationGrade.EligibleGrade = eligibleGrade;
            tblFederationGrade.CampYearID = campYearID;
            return tblFederationGrade;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FederationID
        {
            get
            {
                return _FederationID;
            }
            set
            {
                OnFederationIDChanging(value);
                ReportPropertyChanging("FederationID");
                _FederationID = StructuralObject.SetValidValue(value, "FederationID");
                ReportPropertyChanged("FederationID");
                OnFederationIDChanged();
            }
        }
        private global::System.Int32 _FederationID;
        partial void OnFederationIDChanging(global::System.Int32 value);
        partial void OnFederationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EligibleGrade
        {
            get
            {
                return _EligibleGrade;
            }
            set
            {
                OnEligibleGradeChanging(value);
                ReportPropertyChanging("EligibleGrade");
                _EligibleGrade = StructuralObject.SetValidValue(value, "EligibleGrade");
                ReportPropertyChanged("EligibleGrade");
                OnEligibleGradeChanged();
            }
        }
        private global::System.Int32 _EligibleGrade;
        partial void OnEligibleGradeChanging(global::System.Int32 value);
        partial void OnEligibleGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampYearID
        {
            get
            {
                return _CampYearID;
            }
            set
            {
                OnCampYearIDChanging(value);
                ReportPropertyChanging("CampYearID");
                _CampYearID = StructuralObject.SetValidValue(value, "CampYearID");
                ReportPropertyChanged("CampYearID");
                OnCampYearIDChanged();
            }
        }
        private global::System.Int32 _CampYearID;
        partial void OnCampYearIDChanging(global::System.Int32 value);
        partial void OnCampYearIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimeInCamp
        {
            get
            {
                return _TimeInCamp;
            }
            set
            {
                OnTimeInCampChanging(value);
                ReportPropertyChanging("TimeInCamp");
                _TimeInCamp = StructuralObject.SetValidValue(value, "TimeInCamp");
                ReportPropertyChanged("TimeInCamp");
                OnTimeInCampChanged();
            }
        }
        private Nullable<global::System.Int32> _TimeInCamp;
        partial void OnTimeInCampChanging(Nullable<global::System.Int32> value);
        partial void OnTimeInCampChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblJCC")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblJCC : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblJCC object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblJCC CreatetblJCC(global::System.Int32 id)
        {
            tblJCC tblJCC = new tblJCC();
            tblJCC.ID = id;
            return tblJCC;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FederationID
        {
            get
            {
                return _FederationID;
            }
            set
            {
                OnFederationIDChanging(value);
                ReportPropertyChanging("FederationID");
                _FederationID = StructuralObject.SetValidValue(value, "FederationID");
                ReportPropertyChanged("FederationID");
                OnFederationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FederationID;
        partial void OnFederationIDChanging(Nullable<global::System.Int32> value);
        partial void OnFederationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CampYearid
        {
            get
            {
                return _CampYearid;
            }
            set
            {
                OnCampYearidChanging(value);
                ReportPropertyChanging("CampYearid");
                _CampYearid = StructuralObject.SetValidValue(value, "CampYearid");
                ReportPropertyChanged("CampYearid");
                OnCampYearidChanged();
            }
        }
        private Nullable<global::System.Int32> _CampYearid;
        partial void OnCampYearidChanging(Nullable<global::System.Int32> value);
        partial void OnCampYearidChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblMetaCamp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMetaCamp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMetaCamp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblMetaCamp CreatetblMetaCamp(global::System.Int32 id)
        {
            tblMetaCamp tblMetaCamp = new tblMetaCamp();
            tblMetaCamp.ID = id;
            return tblMetaCamp;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CampName
        {
            get
            {
                return _CampName;
            }
            set
            {
                OnCampNameChanging(value);
                ReportPropertyChanging("CampName");
                _CampName = StructuralObject.SetValidValue(value, true, "CampName");
                ReportPropertyChanged("CampName");
                OnCampNameChanged();
            }
        }
        private global::System.String _CampName;
        partial void OnCampNameChanging(global::System.String value);
        partial void OnCampNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewCampName
        {
            get
            {
                return _NewCampName;
            }
            set
            {
                OnNewCampNameChanging(value);
                ReportPropertyChanging("NewCampName");
                _NewCampName = StructuralObject.SetValidValue(value, true, "NewCampName");
                ReportPropertyChanged("NewCampName");
                OnNewCampNameChanged();
            }
        }
        private global::System.String _NewCampName;
        partial void OnNewCampNameChanging(global::System.String value);
        partial void OnNewCampNameChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblMetaFederationGrade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMetaFederationGrade : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMetaFederationGrade object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="fedID">Initial value of the FedID property.</param>
        /// <param name="fromGrade">Initial value of the FromGrade property.</param>
        /// <param name="toGrade">Initial value of the ToGrade property.</param>
        /// <param name="campYearID">Initial value of the CampYearID property.</param>
        public static tblMetaFederationGrade CreatetblMetaFederationGrade(global::System.Int32 id, global::System.Int32 fedID, global::System.Int32 fromGrade, global::System.Int32 toGrade, global::System.Int32 campYearID)
        {
            tblMetaFederationGrade tblMetaFederationGrade = new tblMetaFederationGrade();
            tblMetaFederationGrade.ID = id;
            tblMetaFederationGrade.FedID = fedID;
            tblMetaFederationGrade.FromGrade = fromGrade;
            tblMetaFederationGrade.ToGrade = toGrade;
            tblMetaFederationGrade.CampYearID = campYearID;
            return tblMetaFederationGrade;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FedID
        {
            get
            {
                return _FedID;
            }
            set
            {
                OnFedIDChanging(value);
                ReportPropertyChanging("FedID");
                _FedID = StructuralObject.SetValidValue(value, "FedID");
                ReportPropertyChanged("FedID");
                OnFedIDChanged();
            }
        }
        private global::System.Int32 _FedID;
        partial void OnFedIDChanging(global::System.Int32 value);
        partial void OnFedIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FromGrade
        {
            get
            {
                return _FromGrade;
            }
            set
            {
                OnFromGradeChanging(value);
                ReportPropertyChanging("FromGrade");
                _FromGrade = StructuralObject.SetValidValue(value, "FromGrade");
                ReportPropertyChanged("FromGrade");
                OnFromGradeChanged();
            }
        }
        private global::System.Int32 _FromGrade;
        partial void OnFromGradeChanging(global::System.Int32 value);
        partial void OnFromGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ToGrade
        {
            get
            {
                return _ToGrade;
            }
            set
            {
                OnToGradeChanging(value);
                ReportPropertyChanging("ToGrade");
                _ToGrade = StructuralObject.SetValidValue(value, "ToGrade");
                ReportPropertyChanged("ToGrade");
                OnToGradeChanged();
            }
        }
        private global::System.Int32 _ToGrade;
        partial void OnToGradeChanging(global::System.Int32 value);
        partial void OnToGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CampYearID
        {
            get
            {
                return _CampYearID;
            }
            set
            {
                OnCampYearIDChanging(value);
                ReportPropertyChanging("CampYearID");
                _CampYearID = StructuralObject.SetValidValue(value, "CampYearID");
                ReportPropertyChanged("CampYearID");
                OnCampYearIDChanged();
            }
        }
        private global::System.Int32 _CampYearID;
        partial void OnCampYearIDChanging(global::System.Int32 value);
        partial void OnCampYearIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblNationalCamp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblNationalCamp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblNationalCamp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblNationalCamp CreatetblNationalCamp(global::System.Int32 id)
        {
            tblNationalCamp tblNationalCamp = new tblNationalCamp();
            tblNationalCamp.ID = id;
            return tblNationalCamp;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> CampID
        {
            get
            {
                return _CampID;
            }
            set
            {
                OnCampIDChanging(value);
                ReportPropertyChanging("CampID");
                _CampID = StructuralObject.SetValidValue(value, "CampID");
                ReportPropertyChanged("CampID");
                OnCampIDChanged();
            }
        }
        private Nullable<global::System.Int64> _CampID;
        partial void OnCampIDChanging(Nullable<global::System.Int64> value);
        partial void OnCampIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FederationID
        {
            get
            {
                return _FederationID;
            }
            set
            {
                OnFederationIDChanging(value);
                ReportPropertyChanging("FederationID");
                _FederationID = StructuralObject.SetValidValue(value, "FederationID");
                ReportPropertyChanged("FederationID");
                OnFederationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FederationID;
        partial void OnFederationIDChanging(Nullable<global::System.Int32> value);
        partial void OnFederationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CampYearID
        {
            get
            {
                return _CampYearID;
            }
            set
            {
                OnCampYearIDChanging(value);
                ReportPropertyChanging("CampYearID");
                _CampYearID = StructuralObject.SetValidValue(value, "CampYearID");
                ReportPropertyChanged("CampYearID");
                OnCampYearIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CampYearID;
        partial void OnCampYearIDChanging(Nullable<global::System.Int32> value);
        partial void OnCampYearIDChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblSynagogue")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSynagogue : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSynagogue object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblSynagogue CreatetblSynagogue(global::System.Int32 id)
        {
            tblSynagogue tblSynagogue = new tblSynagogue();
            tblSynagogue.ID = id;
            return tblSynagogue;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FederationID
        {
            get
            {
                return _FederationID;
            }
            set
            {
                OnFederationIDChanging(value);
                ReportPropertyChanging("FederationID");
                _FederationID = StructuralObject.SetValidValue(value, "FederationID");
                ReportPropertyChanged("FederationID");
                OnFederationIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FederationID;
        partial void OnFederationIDChanging(Nullable<global::System.Int32> value);
        partial void OnFederationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CampYearid
        {
            get
            {
                return _CampYearid;
            }
            set
            {
                OnCampYearidChanging(value);
                ReportPropertyChanging("CampYearid");
                _CampYearid = StructuralObject.SetValidValue(value, "CampYearid");
                ReportPropertyChanged("CampYearid");
                OnCampYearidChanged();
            }
        }
        private Nullable<global::System.Int32> _CampYearid;
        partial void OnCampYearidChanging(Nullable<global::System.Int32> value);
        partial void OnCampYearidChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIPMSModel", Name="tblUserCamp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUserCamp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUserCamp object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tblUserCamp CreatetblUserCamp(global::System.Int64 id)
        {
            tblUserCamp tblUserCamp = new tblUserCamp();
            tblUserCamp.ID = id;
            return tblUserCamp;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, "ID");
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value, "UserId");
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int64> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int64> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CampId
        {
            get
            {
                return _CampId;
            }
            set
            {
                OnCampIdChanging(value);
                ReportPropertyChanging("CampId");
                _CampId = StructuralObject.SetValidValue(value, "CampId");
                ReportPropertyChanged("CampId");
                OnCampIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CampId;
        partial void OnCampIdChanging(Nullable<global::System.Int32> value);
        partial void OnCampIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CampYearid
        {
            get
            {
                return _CampYearid;
            }
            set
            {
                OnCampYearidChanging(value);
                ReportPropertyChanging("CampYearid");
                _CampYearid = StructuralObject.SetValidValue(value, "CampYearid");
                ReportPropertyChanged("CampYearid");
                OnCampYearidChanged();
            }
        }
        private Nullable<global::System.Int32> _CampYearid;
        partial void OnCampYearidChanging(Nullable<global::System.Int32> value);
        partial void OnCampYearidChanged();

        #endregion

    }

    #endregion

}
